spring:
  datasource:
    url: jdbc:sqlserver://technonimbus.database.windows.net:1433;database=technonimbus;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: 
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


